Hack to fix oniguruma conflict on CentOS 7
If you have `jq` installed from epel prior to running metal3-dev-env,
`yum update`, there's a conflict when running `yum update` after
enabling the tripleo repos.

```
--> Finished Dependency Resolution
Error: Package: jq-1.6-1.el7.x86_64 (@epel)
           Requires: libonig.so.2()(64bit)
           Removing: oniguruma-5.9.5-3.el7.x86_64 (@epel)
               libonig.so.2()(64bit)
           Updated By: oniguruma-6.7.0-1.el7.x86_64 (delorean-master-testing)
              ~libonig.so.4()(64bit)
```

This introduces a hack to prevent it from being updated in `yum update`,
until this is fixed, we drop CentOS 7 support, or remove the need for
the tripleo repos at all.